
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*' 

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start application services
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for application to be ready
        run: sleep 10  

      - name: Build Docker Image
        run: docker build --no-cache -t cidadelimpa_nova:latest .

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: target/surefire-reports/

      - name: Stop services
        if: always()
        run: docker compose -f docker-compose.yml down

  deploy:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK for Deployment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker Image
        run: docker build --no-cache -t cidadelimpa_nova:latest .

      - name: Push Docker Image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker tag cidadelimpa_nova:latest karolinelays2021/cidadelimpa_nova:latest
          docker push karolinelays2021/cidadelimpa_nova:latest

      - name: Deploy application with Docker Compose
        run: docker compose -f docker-compose.yml up -d --build
